/**
 * Tool Service
 * Manages tool execution and processing
 */
import { saveMessage } from "../db.server";
import AppConfig from "./config.server";

const MAX_CATALOG_PRODUCTS_IN_HISTORY = 10;
const MAX_CATALOG_DESCRIPTION_LENGTH = 150;

/**
 * Creates a tool service instance
 * @returns {Object} Tool service with methods for managing tools
 */
export function createToolService() {
  const internalTools = [
    {
      name: AppConfig.tools.displayProductCardsName,
      description: "Select exact products from the latest search_catalog results to display as product cards. Use this after recommending products from search_catalog so the UI cards match the products mentioned in the answer.",
      input_schema: {
        type: "object",
        properties: {
          product_ids: {
            type: "array",
            items: { type: "string" },
            maxItems: AppConfig.tools.maxProductsToDisplay,
            description: "Product IDs copied exactly from search_catalog results, for example gid://shopify/Product/123."
          },
          product_urls: {
            type: "array",
            items: { type: "string" },
            maxItems: AppConfig.tools.maxProductsToDisplay,
            description: "Product URLs copied exactly from search_catalog results. Use only when product IDs are unavailable."
          },
          product_identifiers: {
            type: "array",
            items: { type: "string" },
            maxItems: AppConfig.tools.maxProductsToDisplay,
            description: "Fallback list of product IDs or URLs copied from search_catalog results."
          }
        },
        additionalProperties: false
      }
    }
  ];

  const getInternalTools = () => internalTools;

  const isInternalTool = (toolName) => internalTools.some((tool) => tool.name === toolName);

  /**
   * Handles a tool error response
   * @param {Object} toolUseResponse - The error response from the tool
   * @param {string} toolName - The name of the tool
   * @param {string} toolUseId - The ID of the tool use request
   * @param {Array} conversationHistory - The conversation history
   * @param {Function} sendMessage - Function to send messages to the client
   * @param {string} conversationId - The conversation ID
   */
  const handleToolError = async (toolUseResponse, toolName, toolUseId, conversationHistory, sendMessage, conversationId) => {
    if (toolUseResponse.error.type === "auth_required") {
      console.log("Auth required for tool:", toolName);
      await addToolResultToHistory(conversationHistory, toolUseId, toolUseResponse.error.data, conversationId);
      sendMessage({ type: 'auth_required' });
    } else {
      console.log("Tool use error", toolUseResponse.error);
      await addToolResultToHistory(conversationHistory, toolUseId, toolUseResponse.error.data, conversationId);
    }
  };

  /**
   * Handles a successful tool response
   * @param {Object} toolUseResponse - The response from the tool
   * @param {string} toolName - The name of the tool
   * @param {string} toolUseId - The ID of the tool use request
   * @param {Array} conversationHistory - The conversation history
   * @param {Array} productsToDisplay - Array to add product results to
   * @param {string} conversationId - The conversation ID
   */
  const handleToolSuccess = async (toolUseResponse, toolName, toolUseId, conversationHistory, productState, conversationId) => {
    let toolResultContent = toolUseResponse.content;

    // Check if this is a product search result
    if (toolName === AppConfig.tools.productSearchName) {
      const latestProducts = processProductSearchResult(toolUseResponse);
      productState.candidates.splice(0, productState.candidates.length, ...latestProducts);
      productState.selected.splice(0, productState.selected.length);
      toolResultContent = compactProductSearchResult(latestProducts);
    }

    addToolResultToHistory(conversationHistory, toolUseId, toolResultContent, conversationId);
  };

  /**
   * Handles internal tools that are not provided by MCP.
   * @param {string} toolName - The name of the internal tool
   * @param {Object} toolArgs - Tool arguments generated by the model
   * @param {string} toolUseId - The ID of the tool use request
   * @param {Array} conversationHistory - The conversation history
   * @param {Object} productState - Current product candidates and selected cards
   * @param {string} conversationId - The conversation ID
   */
  const handleInternalTool = async (toolName, toolArgs, toolUseId, conversationHistory, productState, conversationId) => {
    if (toolName !== AppConfig.tools.displayProductCardsName) {
      throw new Error(`Internal tool ${toolName} not found`);
    }

    const selectedProducts = selectProductsForDisplay(toolArgs, productState.candidates);
    productState.selected.splice(0, productState.selected.length, ...selectedProducts);

    const toolResult = JSON.stringify({
      displayed_product_count: selectedProducts.length,
      displayed_product_ids: selectedProducts.map((product) => product.id)
    });

    await addToolResultToHistory(conversationHistory, toolUseId, toolResult, conversationId);
  };

  /**
   * Processes product search results
   * @param {Object} toolUseResponse - The response from the tool
   * @returns {Array} Processed product data
   */
  const processProductSearchResult = (toolUseResponse) => {
    try {
      console.log("Processing product search result");
      let products = [];

      if (toolUseResponse.content && toolUseResponse.content.length > 0) {
        const content = toolUseResponse.content[0].text;

        try {
          let responseData;
          if (typeof content === 'object') {
            responseData = content;
          } else if (typeof content === 'string') {
            responseData = JSON.parse(content);
          }

          if (responseData?.products && Array.isArray(responseData.products)) {
            products = responseData.products.map(formatProductData);

            console.log(`Found ${products.length} product candidates`);
          }
        } catch (e) {
          console.error("Error parsing product data:", e);
        }
      }

      return products;
    } catch (error) {
      console.error("Error processing product search results:", error);
      return [];
    }
  };

  /**
   * Formats a product data object
   * @param {Object} product - Raw product data
   * @returns {Object} Formatted product data
   */
  const formatProductData = (product) => {
    const minPrice = product.price_range?.min;
    const maxPrice = product.price_range?.max;

    const formatPrice = (price) => {
      return `${price.currency} ${(price.amount / 100).toFixed(2)}`;
    };

    const price = minPrice && maxPrice
      ? minPrice.amount === maxPrice.amount
        ? formatPrice(minPrice)
        : `${formatPrice(minPrice)} - ${formatPrice(maxPrice)}`
      : 'Price not available';

    const imageUrl =
      product.media?.find((media) => media?.type === 'image')?.url ||
      product.media?.[0]?.url ||
      product.variants?.[0]?.media?.find((media) => media?.type === 'image')?.url ||
      product.variants?.[0]?.media?.[0]?.url ||
      '';

    const description = typeof product.description === 'string'
      ? product.description
      : product.description?.html || '';

    return {
      id: product.product_id || product.id || `product-${Math.random().toString(36).substring(7)}`,
      title: product.title || 'Product',
      price: price,
      image_url: imageUrl,
      description,
      url: product.url || ''
    };
  };

  const compactProductSearchResult = (products = []) => {
    return JSON.stringify({
      products: products
        .slice(0, MAX_CATALOG_PRODUCTS_IN_HISTORY)
        .map((product) => ({
          id: product.id,
          title: product.title,
          price: product.price,
          url: product.url,
          image_url: product.image_url,
          description: truncateText(stripHtml(product.description), MAX_CATALOG_DESCRIPTION_LENGTH)
        })),
      result_count: products.length,
      note: "Compacted search_catalog result. Use exact product ids when calling display_product_cards."
    });
  };

  const stripHtml = (value = '') => {
    return String(value).replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
  };

  const truncateText = (value = '', maxLength) => {
    const text = String(value).trim();

    if (text.length <= maxLength) {
      return text;
    }

    return `${text.slice(0, maxLength).trim()}...`;
  };

  /**
   * Selects display products by exact ID or URL from the latest catalog results.
   * @param {Object} toolArgs - Arguments from display_product_cards
   * @param {Array} candidateProducts - Products from the latest search_catalog result
   * @returns {Array} Products to display as cards
   */
  const selectProductsForDisplay = (toolArgs = {}, candidateProducts = []) => {
    const identifiers = [
      ...(Array.isArray(toolArgs.product_ids) ? toolArgs.product_ids : []),
      ...(Array.isArray(toolArgs.product_urls) ? toolArgs.product_urls : []),
      ...(Array.isArray(toolArgs.product_identifiers) ? toolArgs.product_identifiers : [])
    ]
      .map(normalizeIdentifier)
      .filter(Boolean);

    if (identifiers.length === 0 || candidateProducts.length === 0) {
      return [];
    }

    const selectedProducts = [];
    const selectedIds = new Set();

    identifiers.forEach((identifier) => {
      const product = candidateProducts.find((candidate) => {
        return getProductIdentifiers(candidate).some((candidateIdentifier) => candidateIdentifier === identifier);
      });

      if (product && !selectedIds.has(product.id)) {
        selectedProducts.push(product);
        selectedIds.add(product.id);
      }
    });

    return selectedProducts.slice(0, AppConfig.tools.maxProductsToDisplay);
  };

  const getProductIdentifiers = (product) => {
    const identifiers = [
      product.id,
      product.url,
      getUrlPath(product.url),
      getUrlHandle(product.url)
    ];

    return identifiers.map(normalizeIdentifier).filter(Boolean);
  };

  const normalizeIdentifier = (identifier) => {
    return String(identifier || '').trim().replace(/\/$/, '').toLowerCase();
  };

  const getUrlPath = (url) => {
    try {
      return new URL(url).pathname;
    } catch (error) {
      return '';
    }
  };

  const getUrlHandle = (url) => {
    const path = getUrlPath(url);
    return path.split('/').filter(Boolean).pop() || '';
  };

  /**
   * Adds a tool result to the conversation history
   * @param {Array} conversationHistory - The conversation history
   * @param {string} toolUseId - The ID of the tool use request
   * @param {string} content - The content of the tool result
   * @param {string} conversationId - The conversation ID
   */
  const addToolResultToHistory = async (conversationHistory, toolUseId, content, conversationId) => {
    const toolResultMessage = {
      role: 'user',
      content: [{
        type: "tool_result",
        tool_use_id: toolUseId,
        content: content
      }]
    };

    // Add to in-memory history
    conversationHistory.push(toolResultMessage);

    // Save to database with special format to indicate tool result
    if (conversationId) {
      try {
        await saveMessage(conversationId, 'user', JSON.stringify(toolResultMessage.content));
      } catch (error) {
        console.error('Error saving tool result to database:', error);
      }
    }
  };

  return {
    getInternalTools,
    isInternalTool,
    handleToolError,
    handleToolSuccess,
    handleInternalTool,
    processProductSearchResult,
    selectProductsForDisplay,
    addToolResultToHistory
  };
}

export default {
  createToolService
};
