# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7b0d858bcd2fb2e2a943668cb2e2624c"
name = "AI Shopping Assistant"
application_url = "https://shop-chat-agent-976732686346.asia-southeast1.run.app/"
embedded = true
handle = "storefront-ai-chat-agent"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_product_listings"

[auth]
redirect_urls = [
  "https://shop-chat-agent-976732686346.asia-southeast1.run.app/auth/callback"
]

[pos]
embedded = false

[customer_authentication]
redirect_uris = [
  "https://shop-chat-agent-976732686346.asia-southeast1.run.app/auth/callback"
]
